### ISSUE TITLE
Upgrade to use vaadin-spring-boot-starter 2.0.0

### ISSUE THREAD

**Issue by sanjuthomas** [vaadin-marcus/spring-boot-todo#2]
Do we have a todo version for vaadin-spring-boot-starter 2.0.0 ?

**Comment by marcushellberg** [comment]
I updated it to use Vaadin 8 last week, it should have picked up the right version from the bom. Realized that the pom was still listing 1.0.0 for the vaadin-spring-boot-starter dependency, so removed that.
